services:
  server:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - database
      - bob-the-broker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      [ "/wait-for-it.sh", "database:5432", "--", "/wait-for-it.sh", "bob-the-broker:50051", "--", "sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4" ]


  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: schemion
    ports:
      - "5432:5432"

  bob-the-broker:
    image: ghcr.io/schemion/bob-the-broker:v2.2
    container_name: bob-the-broker
    ports:
      - "50051:50051"
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: "http://localhost:9000"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data:
  cache:
