"""upgrade tables

Revision ID: 701dcad9ca43
Revises: 1b5444edc5bb
Create Date: 2026-02-10 18:37:51.078563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '701dcad9ca43'
down_revision: Union[str, Sequence[str], None] = '1b5444edc5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

task_status_enum = postgresql.ENUM(
    "queued",
    "running",
    "succeeded",
    "failed",
    name="task_status",
)

def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')

    task_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "tasks",
        sa.Column(
            "status",
            task_status_enum,
            nullable=False,
            server_default="queued",
        ),
    )

    op.alter_column("tasks", "status", server_default=None)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'num_samples')
    op.drop_column('models', 'status')
    op.drop_column('models', 'version')
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_column('tasks', 'status')
    op.add_column('models', sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('models', sa.Column('status', postgresql.ENUM('pending', 'training', 'completed', 'failed', name='model_status'), autoincrement=False, nullable=False))
    op.add_column('datasets', sa.Column('num_samples', sa.INTEGER(), autoincrement=False, nullable=True))

    task_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
