"""metrics_path field in model table

Revision ID: bbab44c5ffa6
Revises: 701dcad9ca43
Create Date: 2026-03-29 15:23:16.741968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbab44c5ffa6'
down_revision: Union[str, Sequence[str], None] = '701dcad9ca43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('metrics_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'metrics_path')
    # ### end Alembic commands ###
